### ISSUE TITLE
Overall consistency checks

### ISSUE THREAD

**Issue by whoisjustinngo** [AY2122S1-CS2103-T14-4/tp#175]
- [x] code block positioning
- [x] general structure of sections (what's before what, what's after what?)
- [x] logical flow of document and sections (important sections in front)
- [x] tone
- [x] correct syntax (optional? compulsory? consistent with the program?)

**Comment by whoisjustinngo** [comment]
- [ ] fix broken links under using this guide
- [ ] fix unrendered tabled in details tab
- [ ] showpast and showupcoming

**Comment by kslui99** [comment]
### General
- [ ] Some tab names are not capitalised and some are capitalised. Some of them are enclosed in a `code block like this` while some aren't. It'll be better to standardise so that it's clear those refer to tab names
- [ ] Similarly, some model names are capitalised while some aren't, better to standardise, but this is a more trivial issue.

### Using This Guide
- [ ] remember to delete "There is also a command summary table at the end of this document." if not planning to include command summary
- [ ] "specifed" typo
- [ ] suggestion to add example to aid understanding:
`This means that if some command X with effect Y is specifed in the ‘Z tab’ section, the user will only get intended effect Y when X is executed when on the Z tab (unless the user uses convenience commands, or if it is the contacts and details tabs which are highly related, see summary of commands for contacts and details tab).`
Can be rephrased to
`This means that if some command X with effect Y is specified in the ‘Z tab’ section, the user will only get intended effect Y when X is executed when on the Z tab (unless the user uses convenience commands, or if it is the contacts and details tabs which are highly related, see summary of commands for contacts and details tab). For example, the command to mark a Todo as done will work only while the user is on the Todos tab.`

### Convenience Commands
- [ ] "switching between tabs: tab" can be a hyperlink
- [ ] `/schedule add event d/CS2103 meeting fr/1300 to/1500` doesn't work

### Adding a Custom Goal
- [ ] `add d/call 20 clients goal/20 bydate/16-05-2021` and `add d/earn $1000 in commissions goal/1000 bydate/23-07-2021 bytime/1200` are both dates in the past. Better to use dates in the future to make it more realistic.

### Details tab
- [ ] broken link to summary of commands for contacts and details tab

### Changing a client’s status
- [ ] broken link to dashboard

### Schedule tab
- [ ] Update accordingly after Ricky's update

### Deleting an event
- [ ] In my opinion, better to omit "Potential enhancement: to delete multiple Events at once which was already added into the Schedule."

### Listing all todos
- [ ] Sorry can you help me remove "By default, the list of all Todos will be shown upon navigating to the Todos tab."

### Editing a Todo
- [ ] Typo "secified" change to "specified"

**Comment by kslui99** [comment]
## General
- [x] Fix wrong links to module's files (se-edu) instead of our files
- [x] Fix typos: afte, atrributes, correspionding, UnqiueScheduleList, specifiesd, yealy

## Acknowledgements
- [x] Change stack overflow to StackOverflow

## Architecture
- [ ] May need to update sequence diagram after Bryan's update

## UI component
- [x] Remove CustomGoal extra whitespace

## Logic component
- [x] Change "used to change to the tabs" to "used to change to the tab"
- [ ] Relook at sequence diagram and explanation of sequence diagram after Bryan's update

## Model component
- [ ] First diagram *all should be related to the UniqueDATAList arrow, while *filtered should be related to the ModelManager arrow
- [ ] Change "More detailed models of each DATA object" to "More detailed (partial) class diagrams of each DATA class"
- [ ] Relook after Darren's update

## Storage component 
- [ ] Capitalise and replace inappropriate terms in the ScheduleStorage explanation
